# NumPy - Numerical Python

- **Foundational package for numerical computing in Python**  
- It is widely used because of its following capabilities:

  - `ndarray` is an **efficient multidimensional array** for storing and manipulating numerical data.
  - Enables **faster mathematical operations** on entire arrays without writing explicit loops.
  - Supports **linear algebra, random number generation, and Fourier transform capabilities**.
  - Provides a **C API** for connecting NumPy with libraries written in C, C++, or FORTRAN.


## Why NumPy is Efficient for Large Array Data

- **NumPy is majorly used for its efficient handling of large amounts of array data.**
- It provides this efficiency because:
  - NumPy stores data internally in **contiguous memory blocks**, unlike other Python data structures.
  - The **NumPy library is written in C**, allowing it to use memory directly without type checks or other overhead.
  - Its operations perform **complex computations on entire arrays without the need for Python `for` loops.**
  - It **uses less memory** compared to other Python sequences.
    
Example on **how NumPy performs these optimizations will be demonstrated with a small example** in the next section.


In [5]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [7]:
import numpy as np

my_arr = np.arange(1000000)
my_list = list(range(1000000))

print("Time take to multiply entire array with 2: ")
%time for _ in range(10): my_arr2 = my_arr * 2

print("Time take to multiply entire list with 2: ")
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Time take to multiply entire array with 2: 
CPU times: user 23.9 ms, sys: 240 μs, total: 24.2 ms
Wall time: 24.8 ms
Time take to multiply entire list with 2: 
CPU times: user 428 ms, sys: 165 ms, total: 593 ms
Wall time: 599 ms


## The NumPy `ndarray`: A Multidimensional Array Object

One of the **key features of NumPy** is its **N-dimensional array object (`ndarray`)**, which is a **fast and flexible container for large datasets in Python**.

- An `ndarray` is a **generic multidimensional container for homogeneous data**:
  - All elements in the array must be of the **same data type**.
  
- **Every array has:**
  - **`shape`**: A tuple indicating the **size of each dimension** of the array.
  - **`dtype`**: An object describing the **data type of the array**.


In [3]:
#Simple demonstration of numpy

import numpy as np

data = np.random.randn(2,3) #This will create a random array of dimension 2*3
print(data)

#Print the shape
print(f"Shape: {data.shape}")

#Print the datatype
print(f"Datatype: {data.dtype}"),

[[ 0.06589305 -1.80080723 -1.28296313]
 [ 0.56619579  0.62240807  0.73046752]]
Shape: (2, 3)
Datatype: float64


(None,)

## Creating `ndarray`s

There are many ways to create `ndarray`s in NumPy:

1. **Using the `array` function**  
   - Pass a **list or any sequence-like object** (including another array) to generate a new `ndarray`.
   - **Note:** Nested sequences (like a list of equal-length lists) will be converted into a **multidimensional array**.

2. **Arrays of zeros and ones**  
   - Use `np.zeros(shape)` to create an array filled with **zeros**.
   - Use `np.ones(shape)` to create an array filled with **ones**.

3. **Creating an empty array**  
   - Use `np.empty(shape)` to create an array that **may contain zeros or garbage values**, depending on the state of the memory.

4. **Using `arange`**  
   - `np.arange` is an **array-valued version of the built-in Python `range` function**.

**Note:**  
The **number of dimensions** of an array can be found using the **`ndim` attribute**.


In [4]:
#Method 1
list_data = [1,2,3,4,5]
arr1 = np.array(list_data)
print(f"Array 1: {arr1}")

#Multidimensional array
multidim_arr = np.array([[3,4,5],[2,3,4]])
print(f"Multidimensional array: {multidim_arr}")
print(f"Number of dimensions: {multidim_arr.ndim}")

#Method 2
arr2 = np.zeros((2,3))    #Here remember we have to pass tuple of dimension
print(f"Array 2: {arr2}")
arr2 = np.ones((2,3))
print(f"Array 2: {arr2}")

#Method 3
arr3 = np.empty((2,3))
print(f"Array 3: {arr3}")

#Method 4
arr4 = np.arange(15)
print(f"Array 4: {arr4}")

Array 1: [1 2 3 4 5]
Multidimensional array: [[3 4 5]
 [2 3 4]]
Number of dimensions: 2
Array 2: [[0. 0. 0.]
 [0. 0. 0.]]
Array 2: [[1. 1. 1.]
 [1. 1. 1.]]
Array 3: [[1. 1. 1.]
 [1. 1. 1.]]
Array 4: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## Array Creation Functions in NumPy

| **Name**        | **Syntax**                                | **Description**                                                                                                                                 |
|-----------------|-------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------|
| `array`         | `np.array(data, dtype=None)`             | Converts input data (list, tuple, array, or other sequence) to an `ndarray` by inferring or explicitly specifying `dtype`; copies data by default. |
| `asarray`       | `np.asarray(data, dtype=None)`           | Converts input to `ndarray`, **does not copy** if the input is already an `ndarray`.                                                            |
| `arange`        | `np.arange(start, stop, step)`           | Like the built-in `range` but returns an `ndarray` instead of a list.                                                                          |
| `ones`, `ones_like` | `np.ones(shape, dtype=None)`, `np.ones_like(a)` | Produces an array of all 1s with the given shape and dtype; `ones_like` creates a ones array of the **same shape and dtype as another array**.  |
| `zeros`, `zeros_like` | `np.zeros(shape, dtype=None)`, `np.zeros_like(a)` | Like `ones` and `ones_like` but producing arrays of 0s instead.                                                                                |
| `empty`, `empty_like` | `np.empty(shape, dtype=None)`, `np.empty_like(a)` | Creates new arrays by allocating memory without populating values (may contain garbage values).                                                |
| `full`, `full_like`   | `np.full(shape, fill_value, dtype=None)`, `np.full_like(a, fill_value)` | Produces an array of the given shape and dtype with all values set to the indicated “fill value”; `full_like` uses another array’s shape and dtype. |
| `eye`, `identity`     | `np.eye(N)`, `np.identity(N)`       | Creates a square N × N **identity matrix** (1s on the diagonal, 0s elsewhere).                                                                 |
