# NumPy - Numerical Python

- **Foundational package for numerical computing in Python**  
- It is widely used because of its following capabilities:

  - `ndarray` is an **efficient multidimensional array** for storing and manipulating numerical data.
  - Enables **faster mathematical operations** on entire arrays without writing explicit loops.
  - Supports **linear algebra, random number generation, and Fourier transform capabilities**.
  - Provides a **C API** for connecting NumPy with libraries written in C, C++, or FORTRAN.


## Why NumPy is Efficient for Large Array Data

- **NumPy is majorly used for its efficient handling of large amounts of array data.**
- It provides this efficiency because:
  - NumPy stores data internally in **contiguous memory blocks**, unlike other Python data structures.
  - The **NumPy library is written in C**, allowing it to use memory directly without type checks or other overhead.
  - Its operations perform **complex computations on entire arrays without the need for Python `for` loops.**
  - It **uses less memory** compared to other Python sequences.
    
Example on **how NumPy performs these optimizations will be demonstrated with a small example** in the next section.


In [74]:
import numpy as np

my_arr = np.arange(1000000)
my_list = list(range(1000000))

print("Time take to multiply entire array with 2: ")
%time for _ in range(10): my_arr2 = my_arr * 2

print("Time take to multiply entire list with 2: ")
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Time take to multiply entire array with 2: 
CPU times: user 25.3 ms, sys: 3.87 ms, total: 29.2 ms
Wall time: 30.1 ms
Time take to multiply entire list with 2: 
CPU times: user 381 ms, sys: 164 ms, total: 545 ms
Wall time: 550 ms


## The NumPy `ndarray`: A Multidimensional Array Object

One of the **key features of NumPy** is its **N-dimensional array object (`ndarray`)**, which is a **fast and flexible container for large datasets in Python**.

- An `ndarray` is a **generic multidimensional container for homogeneous data**:
  - All elements in the array must be of the **same data type**.
  
- **Every array has:**
  - **`shape`**: A tuple indicating the **size of each dimension** of the array.
  - **`dtype`**: An object describing the **data type of the array**.


In [75]:
#Simple demonstration of numpy

import numpy as np

data = np.random.randn(2,3) #This will create a random array of dimension 2*3
print(data)

#Print the shape
print(f"Shape: {data.shape}")

#Print the datatype
print(f"Datatype: {data.dtype}"),

[[ 0.7347131  -0.86720006  0.91134969]
 [ 1.31663266 -1.11798033  1.12641784]]
Shape: (2, 3)
Datatype: float64


(None,)

## Creating `ndarray`s

There are many ways to create `ndarray`s in NumPy:

1. **Using the `array` function**  
   - Pass a **list or any sequence-like object** (including another array) to generate a new `ndarray`.
   - **Note:** Nested sequences (like a list of equal-length lists) will be converted into a **multidimensional array**.

2. **Arrays of zeros and ones**  
   - Use `np.zeros(shape)` to create an array filled with **zeros**.
   - Use `np.ones(shape)` to create an array filled with **ones**.

3. **Creating an empty array**  
   - Use `np.empty(shape)` to create an array that **may contain zeros or garbage values**, depending on the state of the memory.

4. **Using `arange`**  
   - `np.arange` is an **array-valued version of the built-in Python `range` function**.

**Note:**  
The **number of dimensions** of an array can be found using the **`ndim` attribute**.


In [76]:
#Method 1
list_data = [1,2,3,4,5]
arr1 = np.array(list_data)
print(f"Array 1: {arr1}")

#Multidimensional array
multidim_arr = np.array([[3,4,5],[2,3,4]])
print(f"Multidimensional array: {multidim_arr}")
print(f"Number of dimensions: {multidim_arr.ndim}")

#Method 2
arr2 = np.zeros((2,3))    #Here remember we have to pass tuple of dimension
print(f"Array 2: {arr2}")
arr2 = np.ones((2,3))
print(f"Array 2: {arr2}")

#Method 3
arr3 = np.empty((2,3))
print(f"Array 3: {arr3}")

#Method 4
arr4 = np.arange(15)
print(f"Array 4: {arr4}")

Array 1: [1 2 3 4 5]
Multidimensional array: [[3 4 5]
 [2 3 4]]
Number of dimensions: 2
Array 2: [[0. 0. 0.]
 [0. 0. 0.]]
Array 2: [[1. 1. 1.]
 [1. 1. 1.]]
Array 3: [[1. 1. 1.]
 [1. 1. 1.]]
Array 4: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## Array Creation Functions in NumPy

| **Name**        | **Syntax**                                | **Description**                                                                                                                                 |
|-----------------|-------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------|
| `array`         | `np.array(data, dtype=None)`             | Converts input data (list, tuple, array, or other sequence) to an `ndarray` by inferring or explicitly specifying `dtype`; copies data by default. |
| `asarray`       | `np.asarray(data, dtype=None)`           | Converts input to `ndarray`, **does not copy** if the input is already an `ndarray`.                                                            |
| `arange`        | `np.arange(start, stop, step)`           | Like the built-in `range` but returns an `ndarray` instead of a list.                                                                          |
| `ones`, `ones_like` | `np.ones(shape, dtype=None)`, `np.ones_like(a)` | Produces an array of all 1s with the given shape and dtype; `ones_like` creates a ones array of the **same shape and dtype as another array**.  |
| `zeros`, `zeros_like` | `np.zeros(shape, dtype=None)`, `np.zeros_like(a)` | Like `ones` and `ones_like` but producing arrays of 0s instead.                                                                                |
| `empty`, `empty_like` | `np.empty(shape, dtype=None)`, `np.empty_like(a)` | Creates new arrays by allocating memory without populating values (may contain garbage values).                                                |
| `full`, `full_like`   | `np.full(shape, fill_value, dtype=None)`, `np.full_like(a, fill_value)` | Produces an array of the given shape and dtype with all values set to the indicated “fill value”; `full_like` uses another array’s shape and dtype. |
| `eye`, `identity`     | `np.eye(N)`, `np.identity(N)`       | Creates a square N × N **identity matrix** (1s on the diagonal, 0s elsewhere).                                                                 |


## Data Types of NumPy `ndarray`s

NumPy provides a **rich set of data types (`dtype`)** for efficient and precise storage of numerical and other data within `ndarray`s. Choosing the right `dtype` helps in:

✅ **Memory optimization** when working with large datasets  
✅ **Ensuring compatibility** with C and FORTRAN libraries  
✅ **Precision control** in numerical computations

---

### Table: Common NumPy Data Types

| **Type** | **Type Code** | **Description** |
|----------|---------------|-----------------|
| `int8`, `uint8` | `i1`, `u1` | Signed and unsigned 8-bit (1 byte) integer types |
| `int16`, `uint16` | `i2`, `u2` | Signed and unsigned 16-bit integer types |
| `int32`, `uint32` | `i4`, `u4` | Signed and unsigned 32-bit integer types |
| `int64`, `uint64` | `i8`, `u8` | Signed and unsigned 64-bit integer types |
| `float16` | `f2` | Half-precision floating point |
| `float32` | `f4` or `f` | Standard single-precision floating point (compatible with C `float`) |
| `float64` | `f8` or `d` | Standard double-precision floating point (compatible with C `double` and Python `float`) |
| `float128` | `f16` or `g` | Extended-precision floating point |
| `complex64`, `complex128`, `complex256` | `c8`, `c16`, `c32` | Complex numbers represented by two 32, 64, or 128-bit floats respectively |
| `bool` | `?` | Boolean type storing `True` and `False` values |
| `object` | `O` | Python object type; elements can be any Python object |
| `string_` | `S` | Fixed-length ASCII string type (1 byte per character); e.g., `'S10'` for 10-character strings |
| `unicode_` | `U` | Fixed-length Unicode string type; platform-dependent byte size; e.g., `'U10'` for 10-character Unicode strings |

---

### Additional Notes

✅ The **`dtype` attribute** of an `ndarray` shows the data type of its elements:
```python
import numpy as np
arr = np.array([1, 2, 3], dtype=np.int32)
print(arr.dtype)  # Output: int32


In [77]:
arr1 = np.array([1,2,3,4], dtype= np.float64)
print(arr1.dtype)
arr2 = np.array([1,2,3,4], dtype= np.int32)
print(arr2.dtype)

float64
int32


## Type Casting with `astype` in NumPy

You can **explicitly convert (cast) an array from one `dtype` to another** using the **`astype` method** of `ndarray`.

### Key Points:

✅ If you **cast floating-point numbers to an integer `dtype`**, the **decimal part will be truncated** (not rounded).  
✅ If you have an **array of strings representing numbers**, you can use `astype` to convert them to **numeric form** for computations.

### Note:
- Caution on numpy.string_ Type
- The numpy.string_ type has a fixed size and may truncate input strings without warning.
- For handling non-numeric or text data, it is often better to use pandas, which provides more intuitive behavior for variable-length string data.

**Calling astype always creates a new array (a copy of the data), even if the new dtype is the same as the old dtype.**

In [78]:
import numpy as np

# Floating-point to integer (decimal part truncated)
arr_float = np.array([3.7, 1.2, -2.8])
arr_int = arr_float.astype(np.int32)
print(arr_int)

# Strings representing numbers to numeric
arr_str = np.array(['1.5', '2.3', '3.7'])
arr_float_from_str = arr_str.astype(np.float64)
print(arr_float_from_str)

[ 3  1 -2]
[1.5 2.3 3.7]


## Vectorization and Broadcasting in NumPy

Arrays are important in NumPy because they **enable you to express batch operations on data without writing explicit `for` loops.** This makes your code:

✅ Faster  
✅ Cleaner  
✅ Closer to mathematical notation

---

### Vectorization

✅ **Vectorization** refers to **performing operations on entire arrays without explicit loops**.

✅ Any **arithmetic operations between equal-size arrays apply the operation element-wise.**

### Broadcasting

✅ **Broadcasting** refers to **performing operations on arrays of different shapes and sizes by stretching the smaller array across the larger one automatically to perform element-wise operations**.

This allows:

- Operations between differently shaped arrays without making unnecessary copies.

- Efficient memory and computation for operations like adding a scalar or row/column to an entire matrix.


In [79]:
arr = np.array([[1,2,3], [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [81]:
arr + arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [82]:
arr - arr

array([[0, 0, 0],
       [0, 0, 0]])

In [83]:
1/ arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [84]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [85]:
arr > 3

array([[False, False, False],
       [ True,  True,  True]])

## Basic Indexing and Slicing in NumPy

NumPy provides **powerful and intuitive indexing and slicing capabilities** for working with arrays efficiently.

---

### Assigning Values to Slices

✅ If you assign a **scalar value to a slice**, the value is **propagated (broadcasted) to the entire selection**.

**Example:**
```python
arr[5:8] = 12


In [86]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
print(arr[5])

5


In [88]:
#slice indexing
print(arr[4:7])

[4 5 6]


In [89]:
#assining value to slice
arr[3:6] = 12
print(arr)

[ 0  1  2 12 12 12  6  7  8  9]


## Difference Between NumPy Views and Python List Copies

Understanding how **slicing behaves in NumPy arrays vs. Python lists** is essential for efficient data manipulation.

---

### Python Lists: Slicing Creates Copies

✅ When you slice a Python list, it **creates a new independent copy** of the data.

✅ Modifying the slice **does *not* affect the original list.**



In [90]:
lst = [1, 2, 3, 4, 5]
sub_lst = lst[1:4]
sub_lst[0] = 99

print(lst)       # [1, 2, 3, 4, 5]
print(sub_lst)   # [99, 3, 4]

[1, 2, 3, 4, 5]
[99, 3, 4]


### NumPy Arrays: Slicing Creates Views

✅ When you slice a NumPy array, it **creates a view on the same data**, not a copy.

✅ Modifying the *slice also modifies* the original array.

✅ NumPy’s behavior is more memory-efficient when working with large datasets, allowing you to modify subarrays without duplicating data.

⚠️ Be cautious: Changes to a slice in NumPy will affect the original array unless you explicitly create a copy using arr.copy().

In [91]:
arr = np.array([1, 2, 3, 4, 5])
sub_arr = arr[1:4]
sub_arr[0] = 99

print(arr)       
print(sub_arr) 

[ 1 99  3  4  5]
[99  3  4]


In [92]:
#Creating copy in numpy
arr = np.array([1,2,3,4,5])
sub_arr = arr[1:4].copy()
sub_arr[0] = 99

print(arr)       
print(sub_arr)   # [99, 3, 4

[1 2 3 4 5]
[99  3  4]


### Indexing in higher dimensions

- With higher dimensional arrays, you have many more options. In a two-dimensional array, the elements at each index are no longer scalars but rather one-dimensional arrays.
- Thus, individual elements can be accessed recursively. But that is a bit too much
work, so you can pass a comma-separated list of indices to select individual elements.

In [93]:
arr = np.array([[1,2,3,4],[2,3,4,5],[2,3,4,5]])
arr

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [2, 3, 4, 5]])

In [94]:
arr[2]

array([2, 3, 4, 5])

In [95]:
arr[2][3]

np.int64(5)

In [96]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [97]:
# Although arr3d[0][1] produces same result, it is efficient as it not invloves creating intermidiate array
arr3d[0,1] 

array([4, 5, 6])

In [98]:
# Slicing to next level
arr = np.array([[1,2,3],[2,3,4],[7,8,9],[10,22,12]])
#This is same like select first two rows
print(arr[:2])
#This is same like select last two rows
print(arr[2:])

[[1 2 3]
 [2 3 4]]
[[ 7  8  9]
 [10 22 12]]


In [99]:
#By mixing integer indexes and slices, you get lower dimensional slices.
print(arr[:2, 1:])

[[2 3]
 [3 4]]


In [100]:
print(arr[:2, 2])

[3 4]


## Boolean Indexing

In [101]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [102]:
data = np.random.randn(7, 4)
data

array([[-1.02893324,  1.53800869, -0.61695107,  1.85992477],
       [ 0.77088104, -0.6962631 , -2.11491483, -0.20484649],
       [-0.63544551, -1.45422133,  0.12000618, -0.32408359],
       [-2.06215417,  0.42129949,  0.45508316,  0.09199927],
       [ 2.23133134,  0.65344792,  0.35691249, -0.728247  ],
       [-0.13548186, -0.6659837 , -1.61020347, -0.05931129],
       [-1.05294886,  0.72340392,  0.55991779, -0.21583404]])

In [103]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [104]:
data[names=='Bob']

array([[-1.02893324,  1.53800869, -0.61695107,  1.85992477],
       [-2.06215417,  0.42129949,  0.45508316,  0.09199927]])

In [105]:
data[~(names=='Bob')]

array([[ 0.77088104, -0.6962631 , -2.11491483, -0.20484649],
       [-0.63544551, -1.45422133,  0.12000618, -0.32408359],
       [ 2.23133134,  0.65344792,  0.35691249, -0.728247  ],
       [-0.13548186, -0.6659837 , -1.61020347, -0.05931129],
       [-1.05294886,  0.72340392,  0.55991779, -0.21583404]])

In [70]:
#In numpy we use | and &, not normal and, or
mask = (names == 'Bob') | (names == 'Will')
data[mask]

array([[-1.45099971, -1.18867856, -1.32114016,  0.79269043],
       [ 0.28286129,  1.12797942, -0.75316113, -0.29184351],
       [ 0.96496895,  0.79280858, -0.3460665 , -0.24722648],
       [ 1.53054507,  0.27077   , -2.0078455 ,  1.88069991]])

In [106]:
#To set all of the negative values in data to 0
data[data<0] = 0
data

array([[0.        , 1.53800869, 0.        , 1.85992477],
       [0.77088104, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.12000618, 0.        ],
       [0.        , 0.42129949, 0.45508316, 0.09199927],
       [2.23133134, 0.65344792, 0.35691249, 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.72340392, 0.55991779, 0.        ]])

## Fancy Indexing

Fancy indexing is a term adopted by NumPy to describe indexing using integer arrays.

In [107]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [110]:
#To select out a subset of the rows in a particular order, you can simply pass a list or ndarray of integers specifying the desired order
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [112]:
#Using negative indices selects rows from the end
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [113]:
#Passing multiple index arrays does something slightly different
#it selects a one-dimensional array of elements corresponding to each tuple of indices
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [114]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]
#Here the elements (1, 0), (5, 3), (7, 1), and (2, 2) were selected

array([ 4, 23, 29, 10])

In [115]:
#The behavior of fancy indexing in this case is a bit different from what some users might have expected
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

## Transposing Arrays and Swapping Axes

### Transposing Arrays

✅ **Transposing** is a **special form of reshaping** in NumPy that **returns a *view* on the underlying data without copying anything**.

✅ This allows you to **rearrange the axes of an array efficiently for numerical computations** without additional memory overhead.

---

### Methods to Transpose

1️⃣ **Using the `transpose` method**
2️⃣ **Using the special `.T` attribute**

- Both methods swap the axes of the array to produce the transposed view.

✅ **Transposing and swapping axes are essential when**:

- Performing matrix operations.

- Adjusting axes to match expected input shapes for functions.

- Rearranging data layouts without copying, ensuring efficient memory usage.

In [116]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [117]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [118]:
arr.transpose()

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [119]:
# For higher dimensional arrays, transpose will accept a tuple of axis numbers to per‐ mute the axes
arr = np.arange(16).reshape((2, 2, 4))
arr.transpose((1, 0, 2))
# Here, the axes have been reordered with the second axis first, the first axis second,and the last axis unchanged.

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [121]:
# Simple transposing with .T is a special case of swapping axes
# ndarray has the method swapaxes, which takes a pair of axis numbers and switches the indicated axes to rearrange the data
arr.swapaxes(1, 2)
#swapaxes similarly returns a view on the data without making a copy.

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

## Universal Functions (ufuncs): Fast Element-Wise Array Functions

A **universal function (ufunc)** in NumPy is a **function that performs fast, element-wise operations on `ndarray` data.**

You can think of ufuncs as **fast, vectorized wrappers around functions that take one or more scalar inputs and produce one or more scalar outputs.**

Ufuncs help in:
✅ Writing cleaner, loop-free numerical code  
✅ Utilizing optimized, compiled C backend for speed  
✅ Expressing element-wise operations naturally

---

## Table: Unary Universal Functions

| **Function** | **Description** |
|--------------|-----------------|
| `abs`, `fabs` | Compute the absolute value element-wise for integer, float, or complex values |
| `sqrt` | Compute the square root of each element (`arr ** 0.5`) |
| `square` | Compute the square of each element (`arr ** 2`) |
| `exp` | Compute the exponent *e^x* of each element |
| `log`, `log10`, `log2`, `log1p` | Natural log, log base 10, log base 2, log(1 + x) |
| `sign` | Compute the sign of each element: 1 (positive), 0 (zero), -1 (negative) |
| `ceil` | Compute the ceiling (smallest integer >= element) |
| `floor` | Compute the floor (largest integer <= element) |
| `rint` | Round to nearest integer, preserving dtype |
| `modf` | Return fractional and integral parts of each element as separate arrays |
| `isnan` | Boolean array indicating whether each value is NaN |
| `isfinite`, `isinf` | Boolean array indicating whether each value is finite or infinite |
| `cos`, `cosh`, `sin`, `sinh`, `tan`, `tanh` | Regular and hyperbolic trigonometric functions |
| `arccos`, `arccosh`, `arcsin`, `arcsinh`, `arctan`, `arctanh` | Inverse trigonometric functions |
| `logical_not` | Compute truth value of `not x` element-wise (equivalent to `~arr`) |

---

## Table: Binary Universal Functions

| **Function** | **Description** |
|--------------|-----------------|
| `add` | Element-wise addition |
| `subtract` | Element-wise subtraction (first - second) |
| `multiply` | Element-wise multiplication |
| `divide`, `floor_divide` | Element-wise division or floor division (truncating remainder) |
| `power` | Raise elements in first array to powers in second array |
| `maximum`, `fmax` | Element-wise maximum (`fmax` ignores NaN) |
| `minimum`, `fmin` | Element-wise minimum (`fmin` ignores NaN) |
| `mod` | Element-wise modulus (remainder after division) |
| `copysign` | Copy sign of values in second array to first array |
| `greater`, `greater_equal`, `less`, `less_equal`, `equal`, `not_equal` | Element-wise comparison, returning boolean arrays (equivalent to `>`, `>=`, `<`, `<=`, `==`, `!=`) |
| `logical_and`, `logical_or`, `logical_xor` | Compute element-wise logical operations |

---


In [123]:
arr = np.arange(10)
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [124]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [125]:
x = np.random.randn(8)
y = np.random.randn(8)
np.maximum(x, y)

array([ 0.76936807, -0.84868543, -0.21508022,  1.45636284,  1.10227754,
        0.33110027,  1.25922736,  0.02411657])

In [127]:
# While not common, a ufunc can return multiple arrays. modf is one example, a vectorized version of the built-in Python divmod; it returns the fractional and integral parts of a floating-point array
arr = np.random.randn(7) * 5
print(arr)
remainder, whole_part = np.modf(arr)
print(remainder)
print(whole_part)

[-1.53019902  0.67623332 -2.32039274  4.09955165 -0.15427852 10.28065319
  1.28714643]
[-0.53019902  0.67623332 -0.32039274  0.09955165 -0.15427852  0.28065319
  0.28714643]
[-1.  0. -2.  4. -0. 10.  1.]


In [128]:
#Ufuncs accept an optional out argument that allows them to operate in-place on arrays
print(arr)
np.sqrt(arr)

[-1.53019902  0.67623332 -2.32039274  4.09955165 -0.15427852 10.28065319
  1.28714643]


/tmp/ipykernel_5808/1663797801.py:3: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([       nan, 0.82233407,        nan, 2.02473496,        nan,
       3.20634577, 1.13452476])

In [129]:
np.sqrt(arr, arr)

/tmp/ipykernel_5808/269955669.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr, arr)


array([       nan, 0.82233407,        nan, 2.02473496,        nan,
       3.20634577, 1.13452476])

In [130]:
arr

array([       nan, 0.82233407,        nan, 2.02473496,        nan,
       3.20634577, 1.13452476])